# Generated by Django 2.2 on 2021-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0002_remove_bucketlist_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlistlocation',
            name='list_num',
            field=models.IntegerField(null=True),
        ),
    ]
